import type { MarketInstrument } from "@/lib/technical-engine";

// Common shares on SET and mai. The list intentionally excludes DW, DR, ETF,
// warrants and non-voting receipts because they distort an equity scanner.
const symbols = `
2S 3K-BAT 7UP A A5 AAI AAV ABM ACC ACE ACG ADVANC AEONTS AF AH AHC AI AIE AIT AJ AKP AKR ALLA ALT ALUCON AMA AMANAH AMARIN AMATA AMATAV AMC AMR ANAN AOT AP APCO APCS APP APPLE AQUA ARIN ARIP AS ASIAN ASAP ASEFA ASIA ASIMAR ASK ASN ASP ASW ATP30 AU AUCT AURA AWC AYUD B BA BAFS BAM BANPU BAT-3K BAY BBIK BBL BCH BCP BCPG BDMS BEAUTY BEC BEM BEYOND BGC BGRIM BH BIG BIZ BJC BJCHI BKD BLA BLC BLESS BLISS BM BOL BPP BR BRR BSBM BTC BTG BTS BTW BUI BWG BYD CBG CCET CCP CEN CENTEL CFRESH CH CHASE CHEWA CHG CHOTI CHOW CI CIG CIMBT CITY CIVIL CK CKP CM CMC CMR CNT COLOR COM7 CPALL CPANEL CPF CPH CPICO CPL CPN CPW CRC CRD CSC CSP CSR CSS CTW CV D DD DDD DELTA DEMCO DITTO DOD DOHOME DPAINT DRT DUSIT DV8 EA EASTW ECF ECL EE EFORL EGCO EPG ERW ETC EVER F&D FANCY FE FLOYD FN FORTH FPI FPT FSMART FSS GABLE GC GUNKUL GFPT GGC GLOBAL GLOCON GLORY GPSC GRAMMY GRAND GREEN GULF GYT HANA HARN HFT HMPRO HTECH HUMAN ICC ICHI ICN IFEC III ILINK ILM IMH IND INET INGRS INOX INSURE INTUCH IP IRCP IRPC IT ITC ITD ITEL ITNS IVL J JAK JAS JCK JDF JMART JMT JR JTS KAMART KBANK KBS KC KCE KCM KDH KEX KGI KISS KKC KKP KOOL KSL KTB KTC KTIS KUMWEL KUN KWC KWM L&E LALIN LANNA LH LHFG LHK LIT LOXLEY LPH LST M MACO MAJOR MAKRO MALEE MANRIN MASTER MATCH MATI MAX MBK MC M-CHAI MCOT MCS MDX MEGA META MFEC MGI MGT MINT MITSIB MK MODERN MONO MORE MOSHI MSC MST MTC MTI MVP NC NCH NFC NKI NOBLE NPK NRF NSI NTV NUSA NVD NWR NYT OGC OISHI ONEE OR ORI OSP OTO PACO PAP PATO PDG PDJ PEACE PERM PF PG PHOL PIN PJW PLANB PLANET PLAT PLUS PM PMTA POLY PORT POST PPM PPP PRAKIT PR9 PRAPAT PREB PRECHA PRIME PRINC PRIN PRM PROEN PROS PROUD PSL PT PTC PTT PTTEP PTTGC Q-CON QH QTC RABBIT RAM RATCH RBF RCL RICHY RJH ROJNA RPC RPH RSP RT S S11 SABINA SAK SAM SAMART SAMCO SAMTEL SAPPE SAT SAUCE SAWAD SAWANG SC SCB SCC SCCC SCG SCM SCP SDC SE SEAOIL SECURE SENA SENX SFLEX SFT SGC SGF SGP SHR SIAM SICT SIRI SIS SITHAI SK SKN SKY SLP SMART SMD SMIT SMT SNC SNNP SNP SO SOLAR SPA SPC SPG SPI SPRC SR SRICHA SSC SSF SSP SSSC SST STA STANLY STARK STC STEC STGT STI STPI SUC SUN SUSCO SUTHA SVH SVI SVOA SYNTEC TACC TAKUNI TASCO TCAP TCMC TEAMG TEGH TFG TFI THAI THANA THANI THCOM THG THIP THRE THREL TIDLOR TIPH TISCO TITLE TK TKN TKS TKT TLI TM TMD TMT TNDT TNH TNITY TNL TNP TOA TOG TOP TOPP TPAC TPBI TPCS TPLAS TQM TRC TRITN TRT TRU TRUE TSC TSE TSTE TSTH TTA TTB TTCL TTW TU TVDH TVI TVO TWPC UAC UBE UEC UKEM UP UPA UPOIC UV UVAN VARO VIH VL VNG W WARRIX WAVE WFX WGE WHA WHAUP WICE WIIK WIN WINMED WORK WORLD WP WPH XPG YGG YONG ZEN
`.trim().split(/\s+/);

const aliases: Record<string, [string, string]> = {
  ADVANC: ["แอดวานซ์ อินโฟร์ เซอร์วิส", "เทคโนโลยี"], AOT: ["ท่าอากาศยานไทย", "ขนส่ง"],
  BDMS: ["กรุงเทพดุสิตเวชการ", "การแพทย์"], CPALL: ["ซีพี ออลล์", "พาณิชย์"],
  DELTA: ["เดลต้า อีเลคโทรนิคส์", "อิเล็กทรอนิกส์"], GULF: ["กัลฟ์ ดีเวลลอปเมนท์", "พลังงาน"],
  KBANK: ["ธนาคารกสิกรไทย", "ธนาคาร"], KTB: ["ธนาคารกรุงไทย", "ธนาคาร"],
  PTT: ["ปตท.", "พลังงาน"], PTTEP: ["ปตท. สำรวจและผลิตปิโตรเลียม", "พลังงาน"],
  SCB: ["เอสซีบี เอกซ์", "ธนาคาร"], TRUE: ["ทรู คอร์ปอเรชั่น", "เทคโนโลยี"],
};

export const thaiAllUniverse: readonly MarketInstrument[] = [...new Set(symbols)].sort().map((symbol) => {
  const [name, sector] = aliases[symbol] ?? [symbol, "SET / mai"];
  return [symbol, `${symbol}.BK`, name, sector] as const;
});

